apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-dev
  namespace: argocd

spec:
  project: homelab994

  source:
    repoURL: https://github.com/homelab994/gh-newops
    targetRevision: HEAD
    path: clusters/homelab994/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true