replicaCount: 2

activeProfile: dev

image:
  repository: georgerusu994/gh-another-spring
  tag: 26.3.27

service:
  port: 9001

configs:
  base: platform-deployments/configs/base/application.yml
  env: platform-deployments/configs/dev/application-dev.yml
  service: platform-deployments/configs/dev/application-gh-another-spring-dev.yml