name: Deploy artifact

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Artifact name'
        type: string
        required: true
      release-version:
        description: 'Release version'
        type: string
        required: true
      environment:
        description: 'Target environment'
        type: string
        required: true
      target:
        description: 'Specify host or all'
        type: string
        required: false
        default: 'all'
  workflow_dispatch:
    inputs:
      artifact-name:
        description: 'Artifact name'
        type: choice
        options:
          - gh-simple-spring
        required: true
      release-version:
        description: 'Release version'
        type: string
        required: true
      environment:
        description: 'Target environment'
        type: choice
        options:
          - dev
          - int
          - preprod
          - prod
        required: true
      target:
        description: 'Specify host or all'
        type: choice
        options:
          - All
          - Primary
          - Backup
          - Standalone
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.hosts-list.outputs.hosts }}
      hosts-empty: ${{ steps.hosts-list.outputs.hosts-empty }}
    steps:
      - name: Resolve inputs
        id: resolve-inputs
        run: |
          echo "artifact-name=${{ inputs.artifact-name || github.event.inputs.artifact-name }}" >> $GITHUB_OUTPUT
          echo "release-version=${{ inputs.release-version || github.event.inputs.release-version }}" >> $GITHUB_OUTPUT
          echo "environment=${{ inputs.environment || github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          echo "target=${{ inputs.target || github.event.inputs.target }}" >> $GITHUB_OUTPUT

      - name: Get hosts list
        id: hosts-list
        run: |
          ENV="${{ steps.resolve-inputs.outputs.environment }}"
          TARGET="${{ steps.resolve-inputs.outputs.target }}"

          case "$ENV" in
            dev)
              PRIMARY='["dev1.company.com"]'
              BACKUP='[]'
              STANDALONE='[]'
              ;;
            int)
              PRIMARY='["int1.company.com"]'
              BACKUP='["int2.company.com"]'
              STANDALONE='[]'
              ;;
            preprod)
              PRIMARY='["preprod1.company.com"]'
              BACKUP='["preprod2.company.com"]'
              STANDALONE='["preprod3.company.com"]'
              ;;
            prod)
              PRIMARY='["prod1.company.com"]'
              BACKUP='["prod2.company.com"]'
              STANDALONE='["prod3.company.com"]'
              ;;
          esac
          
          if [ "$TARGET" = "Primary" ]; then
            HOSTS=$PRIMARY
          elif [ "$TARGET" = "Backup" ]; then
            HOSTS=$BACKUP
          elif [ "$TARGET" = "Standalone" ]; then
            HOSTS=$STANDALONE
          else
            HOSTS=$(jq -c -n "$PRIMARY + $BACKUP")
          fi
          
          if [ "$HOSTS" = "[]" ]; then
            echo "No hosts available in environment: $ENV for selection: $TARGET"
            echo "hosts-empty=true" >> $GITHUB_OUTPUT
          else
            echo "hosts-empty=false" >> $GITHUB_OUTPUT
          fi
          
          echo "hosts=$HOSTS" >> $GITHUB_OUTPUT

  deploy:
    needs: prepare
    if: needs.prepare.outputs.hosts-empty != 'true'
    runs-on: ubuntu-latest
    environment: ${{ steps.resolve-inputs.outputs.environment }}

    strategy:
      max-parallel: 1
      matrix:
        host: ${{ fromJson(needs.prepare.outputs.hosts) }}

    steps:
      - name: Deploy to ${{ matrix.host }}
        run: |
          echo "HOSTS: ${{ matrix.host }}"
#        uses: appleboy/ssh-action@v1
#        with:
#          host: ${{ matrix.host }}
#          username: deploy
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#            /opt/myapp/deploy.sh \
#              ${{ steps.resolve-inputs.outputs.artifact-name }} \
#              ${{ steps.resolve-inputs.outputs.release-version }} \
#              ${{ steps.resolve-inputs.outputs.environment }}
  update-manifest:
    needs: [ deploy ]
    uses: ./.github/workflows/update-manifest.yml
    with:
      artifact-name: ${{ steps.resolve-inputs.outputs.artifact-name }}
      release-version: ${{ steps.resolve-inputs.outputs.release-version }}
      environment: ${{ steps.resolve-inputs.outputs.environment }}