name: Deploy artifact

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Artifact name'
        type: string
        required: true
      release-version:
        description: 'Release version'
        type: string
        required: true
      environment:
        description: 'Target environment'
        type: string
        required: true
      target:
        description: 'Specify host or all'
        type: string
        required: false
        default: 'all'
  workflow_dispatch:
    inputs:
      artifact-name:
        description: 'Artifact name'
        type: choice
        options:
          - another-service
          - gh-simple-spring
          - inexistent-service
        required: true
      release-version:
        description: 'Release version'
        type: string
        required: true
      environment:
        description: 'Target environment'
        type: choice
        options:
          - DEV
          - INT
          - PREPROD
          - PROD
        required: true
      target:
        description: 'Specify host or all'
        type: choice
        options:
          - 'All'
          - 'Primary'
          - 'Backup'
          - 'Standalone'
        required: false
        default: 'All'

concurrency:
  group: deploy-artifact-${{ inputs.artifact-name }}-env-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.service-type.outputs.type }}
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: homelab994
          repositories: gh-newops

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: homelab994/gh-newops
          token: ${{ steps.app-token.outputs.token }}
          ref: develop

      - name: Get service type
        id: service-type
        run: |
          SERVICE=${{ inputs.artifact-name }}
          TYPE=$(yq ".services[\"$SERVICE\"].type" platform/services.yaml)
          
          echo "type=$TYPE" >> $GITHUB_OUTPUT    

  deploy-vm:
    needs: prepare
    if: needs.prepare.outputs.type == 'vm'
    uses: ./.github/workflows/deploy-vm.yml
    with:
      artifact-name: ${{ inputs.artifact-name }}
      release-version: ${{ inputs.release-version }}
      environment: ${{ inputs.environment }}
      target: ${{ inputs.target }}

  deploy-k8s:
    needs: prepare
    if: needs.prepare.outputs.type == 'k8s'
    uses: ./.github/workflows/deploy-k8s.yml
    with:
      artifact-name: ${{ inputs.artifact-name }}
      release-version: ${{ inputs.release-version }}
      environment: ${{ inputs.environment }}

  manifest:
    needs: [ deploy-vm, deploy-k8s ]
    if: always()
    uses: ./.github/workflows/update-manifest.yml
    with:
      artifact-name: ${{ inputs.artifact-name }}
      release-version: ${{ inputs.release-version }}
      environment: ${{ inputs.environment }}
    secrets: inherit