name: Scheduled Monthly Increment

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - service-name: gh-simple-spring
            repository-name: homelab994/gh-simple-spring
          - service-name: gh-simple-spring
            repository-name: homelab994/gh-simple-spring
    uses: ./.github/workflows/monthly-increment-version.yml
    with:
      service-name: ${{ matrix.service-name }}
      repository-name: ${{ matrix.repository-name }}
    secrets: inherit