name: Monthly Bump Version

on:
  workflow_call:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Bump month version
        id: bump-month
        run: |
          YEAR=$(date -u +%y)
          MONTH=$(date -u +%-m)
          NEW_VERSION="$YEAR.$MONTH.0"
          mvn build-helper:parse-version versions:set \
            -DnewVersion=$NEW_VERSION-SNAPSHOT \
            versions:commit
          echo "new-version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Commit monthly bump
        run: |
          VERSION=${{ steps.bump-month.outputs.new-version }}
          
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git commit -am "v$VERSION released [skip ci]"
          git push origin develop