name: Update Environment Manifest

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Artifact name'
        type: string
        required: true
      release-version:
        description: 'Release version'
        type: string
        required: true
      environment:
        description: 'Target environment'
        type: string
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: homelab994/gh-newops
          token: ${{ steps.app-token.outputs.token }}
          ref: develop
          path: gh-newops

      - name: Verify git repo
        run: |
          git -C gh-newops status

      - name: Debug checkout
        run: |
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -la
          echo "gh-newops contents:"
          ls -la gh-newops

      - name: Update manifest
        run: |
          FILE="gh-newops/vm-manifests/${{ inputs.environment }}.json"
          SERVICE="${{ inputs.artifact-name }}"
          VERSION="${{ inputs.release-version }}"
          
          jq --arg svc "$SERVICE" \
             --arg ver "$VERSION" \
             '.[$svc]=$ver' $FILE > tmp && mv tmp $FILE

          echo "gh-newops contents:"
          cd gh-newops/vm-manifests
          ls -la
          cat ${{ inputs.environment }}.json

      - name: Commit changes
        run: |    
          git -C gh-newops config user.name "github-actions"
          git -C gh-newops config user.email "github-actions@github.com"
          
          git -C gh-newops add vm-manifests/${{ inputs.environment }}.json
          
          if git -C gh-newops diff --cached --quiet; then
            echo "No changes detected. Skipping commit."
            exit 0
          fi
    
          git -C gh-newops commit -m "Update ${{ inputs.artifact-name }} to ${{ inputs.release-version }} in ${{ inputs.environment }}"
          git -C gh-newops push origin develop
